### ISSUE TITLE
Nadir preview only works correctly on one setting

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#16]
When nadir is 23% it renders in preview nadir step perfectly.

If slider is adjusted, a corrupted image is shown.

https://drive.google.com/file/d/1hC0cgcnrjn0PV-8HGrEdejwFsthuAasN/view?usp=sharing

**Comment by superdev0505** [comment]
Fixed

**Comment by himynamesdave** [comment]
closing as done
