### ISSUE TITLE
Allow user to skip all processing steps

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#34]
If images all correctly geotagged (by adding track or because already in image), show user a map view with sequence.

Give user option "looks good", in which goes to integrations or "make changes", where they go to modify spacing page and follow flow as it is now,

![Explorer v2 diagrams](https://user-images.githubusercontent.com/1296409/91015074-75350500-e5e2-11ea-97db-71ca8513ef9d.jpg)

**Comment by himynamesdave** [comment]
@superdev0505 

```
If images all correctly geotagged (by adding track or because already in image), show user a map view with sequence.
```

This should be new page (after add gps track IF required) or after processing (if gps); with map, and buttons "make edits" or "looks good".

If looks good clicked, takes to integrations step

**Comment by superdev0505** [comment]
```
Give user option "looks good", in which goes to add nadir (360) or blur (flat), or "make changes", where they go to modify spacing page and follow flow as it is now,
```
As I checked, first requirement is not new page, right?

**Comment by himynamesdave** [comment]
@superdev0505 

```
If images all correctly geotagged (by adding track or because already in image), show user a map view with sequence.

Give user option "looks good", in which goes to integrations, or "make changes", where they go to modify spacing page and follow flow as it is now,
```

**Comment by himynamesdave** [comment]
@superdev0505 

```
If looks good clicked, takes to integrations step
```

Currently takes user to nadir step. Should be integrations step.

**Comment by himynamesdave** [comment]
@superdev0505 only show button to skip to integrations page on the skip all processing steps page.

(do not show it on the distance modifications, etc, pages)

**Comment by himynamesdave** [comment]
closing as done
