### ISSUE TITLE
Add Mapillary upload destination

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#50]
Mapillary Oauth flow: https://www.mapillary.com/developer/api-documentation/#oauth
Upload imagery: https://www.mapillary.com/developer/api-documentation/#uploading-imagery

Also see: https://github.com/trek-view/mtp-desktop-uploader/tree/develop/integrations

Only upload one copy of image, as documented in #49 

Should capture sequence key (https://www.mapillary.com/developer/api-documentation/#search-sequences)

See workflow here: https://guides.trekview.org/mtp-desktop-uploader/developer-docs/integrations/mapillary

**Comment by himynamesdave** [comment]
@superdev0505 more info in wiki for implementation

https://github.com/trek-view/mtp-desktop-uploader/wiki/functional-information#202-mapillary

**Comment by himynamesdave** [comment]
Some issues on packaged app:

https://trekview.slack.com/files/UL7PGN7J5/F01AKJ6RXD0/annotate-image.webm

**Comment by superdev0505** [comment]
Please check https://trekview.slack.com/archives/D016HNV2WQ3/p1599944372212200

**Comment by himynamesdave** [comment]
on select upload page mapillary tick button state should = map the paths tick button state.

i.e when i tick mapillary, mtpw also ticks. same for untick.

**Comment by himynamesdave** [comment]
just waiting for image to publish on mapillary @superdev0505
