### ISSUE TITLE
Add confirm step to delete sequence

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#72]
If user attemtps to delete sequence, should show warning that all data will be lost

WARNING!
All sequence data (including image files) will be deleted from your computer. Are you sure you want to delete this sequence?

**Comment by himynamesdave** [comment]
@superdev0505 this is implemented BUT,

now when sequence deleted, the raw files remain in /sequence directory

**Comment by superdev0505** [comment]
@himynamesdave 
Please check also https://trekview.slack.com/archives/D016HNV2WQ3/p1599944372212200

**Comment by himynamesdave** [comment]
closing as done
