### ISSUE TITLE
If video file print exiftool telemetry extraction in /originals

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#74]
When we extract telemetry from video we use exiftool.

We should store all the telemetry from video files in SEQUENCE/originals directory (it might be useful in future)

$ exiftool -ee -G3 -s VIDEO.mp4 > VIDEO_telemetry.txt

**Comment by superdev0505** [comment]
@himynamesdave 
I added as json, I hope it's okay for this ticket, as there is no option for https://www.npmjs.com/package/exiftool-vendored

**Comment by himynamesdave** [comment]
closing as done
