### ISSUE TITLE
In sequence list, print local path to image

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#80]
On different systems, the sequence data is printed in different locations.

At bottom of each sequence card in sequence list view show path to sequence directory

**Comment by superdev0505** [comment]
@himynamesdave 
Could you tell me what you mean exactly?

**Comment by himynamesdave** [comment]
![download](https://user-images.githubusercontent.com/1296409/93120526-c4db8d80-f6c3-11ea-860c-3dcde8ee67f4.png)

Like this @superdev0505

**Comment by superdev0505** [comment]
@himynamesdave 
which file should I show?
.json for sequence and photos?

**Comment by himynamesdave** [comment]
closing as done
