### ISSUE TITLE
Issue with photo time offset when adding gpx track

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#81]
Each time, the user changes offset, without confirming, the value shown for first photo time should always be the originaldatetime of unedited photo (raw original).

There is some very odd behaviour which causes photo time to be very confused in current implementation, see video

https://trekview.slack.com/files/UL7PGN7J5/F01AKPZEKPV/if-no-mtp-auth-credentials-in-env-skip-this-step-__-issue-78-__-trek-view-mtp-desktop-uploader.webm

**Comment by superdev0505** [comment]
@himynamesdave 
I want you to explain more.

**Comment by himynamesdave** [comment]
@superdev0505  Do you see the video?

Lets say photo start time is 12:00:00

I click modify time +3600 and select

I then click modify time -5500 and select again. See how some times it seems to cache values?

We should make this simple. As user types in time offset the time gets updated in window before they select.

If user attempts to modify time twice, on second modification attempt show the originaldatetime of image and  modify the originaldatetime of image, (not the previously update request +3600)

**Comment by superdev0505** [comment]
Then it will add -1900 to original photo time.
And we discussed before, and you said me that if then, I had to show the not updated photo time on modify time page, instead of updated photo time.

**Comment by himynamesdave** [comment]
@superdev0505 yes what you describe is correct. but watch the video carefully :)

**Comment by himynamesdave** [comment]
My first photo time (in raw photo file) is 13:32. This shows correctly when first on time mod page.

After modyfying time a few times (3,4,+) the first photo time in modify time DOES not show this value. See it changes to 2020-08-02T10:33:46

```
The start time of your GPX Track is:2020-08-02T11:05:06

The time in the first photo in the sequence is:2020-08-02T10:33:46
```

![Untitled](https://user-images.githubusercontent.com/1296409/93178150-1cb1dd00-f734-11ea-8801-adc698c5221e.png)

**Comment by superdev0505** [comment]
@himynamesdave 
could you explain about logic?

**Comment by himynamesdave** [comment]
On the image above, that time should always show the original time of photo. Always. 

If user updates time, then new time shown on confirm screen. If they decide to change time again, the image time shown time should always show the original time of photo (as per first sentence).

And make sure cache is clear so that the value entry box does not contain a number when user moves back to this screen,

**Comment by himynamesdave** [comment]
https://trekview.slack.com/files/UL7PGN7J5/F01AKJF4F1U/all-error-messages-should-not-persist-between-views-__-issue-83-__-trek-view-mtp-desktop-uploader.webm

**Comment by himynamesdave** [comment]
closing as done
