### ISSUE TITLE
Do not show any integrations if MTP Web not configured

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#82]
All integrations rely on Map the Paths to work correctly (e.g. Mapillary data is sent to MTP web).

If MTP we integration (valid user token for MTP) does not exist, do not show any integrations,

**Comment by superdev0505** [comment]
@himynamesdave 
You mean I have not to show the mapillary integration if MTP web configurations?
Now it's not set then only MTP web login page is not shown.

**Comment by himynamesdave** [comment]
If login page for mtp web not shown (because .env vars do not exist) user is not allowed to use integrations.

Also, on integrations page (if mtpw does exist), should always show Map the Paths web integration (and it is always ticked and cannot be unticked).

**Comment by himynamesdave** [comment]
closing as done
