### ISSUE TITLE
Add ability for user to add copyright data to exif

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#85]
User should be able to do this in nice UI view after heading offset page

* Artist/Copyright
* UserComment

exiftool -artist="XXXX" -copyright="XXXX" -UserComment="xxx"

**Comment by himynamesdave** [comment]
@superdev0505 `usercomment` field does not seem to update

`copyright` and `artist` fields working

**Comment by superdev0505** [comment]
![Uploading image.png…]()

**Comment by superdev0505** [comment]
![Uploading Capture.PNG…]()

**Comment by superdev0505** [comment]
![Capture](https://user-images.githubusercontent.com/38669289/94323783-62be3a80-ff97-11ea-97f8-d8ab42b878b5.PNG)
Please check this image, as you can see, the comments, artist, copyright are updated.
