### ISSUE TITLE
Heading calculations appear incorrect

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#94]
See the attached screenshot. These sequences were created without modifying any heading information.

Therefore it is expected the photos would be each facing each other. As you can see this is not the case. Seems there is some error with the heading calculation.

![Untitled](https://user-images.githubusercontent.com/1296409/94145207-791ea600-fe72-11ea-9eb6-e99bc824b166.png)

**Comment by superdev0505** [comment]
![Capture1](https://user-images.githubusercontent.com/38669289/94323731-3aced700-ff97-11ea-9f5d-3591b6641fcc.PNG)
Please check this image, I processed the video, it works correctly.
So now, I think the images has not correct azimuth.
