### ISSUE TITLE
Place id does not seem to be correctly assigned to uploaded images

### ISSUE THREAD

**Issue by himynamesdave** [trek-view/mtp-desktop-uploader#99]
![f8177f8b-7c3e-4202-b8e0-921831447511](https://user-images.githubusercontent.com/1296409/94232824-1deac300-ff07-11ea-9950-ec7e05805941.png)
![857bcec8-17a6-4c3c-9496-589b54c9dd95](https://user-images.githubusercontent.com/1296409/94232826-1f1bf000-ff07-11ea-9ed4-1da7a74837e7.png)

If placeid added, you would see the place name on the photo in Google maps (first image). In my account shows as unknown place, meaning placeid not added or not added correctly (Second image)

**Comment by superdev0505** [comment]
@himynamesdave 
If then, it seems that we can not add same place id to photos.

**Comment by himynamesdave** [comment]
yes this is possible @superdev0505 

try it using the api -- you will see it is possible

**Comment by superdev0505** [comment]
@himynamesdave
